# Generated by Django 2.2.5 on 2019-10-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_year', models.IntegerField()),
                ('student_region', models.CharField(max_length=3)),
                ('univ_group', models.CharField(max_length=3)),
                ('univ_region', models.CharField(max_length=2)),
                ('major_group', models.CharField(max_length=3)),
                ('univ_name', models.CharField(max_length=10)),
                ('univ_major', models.CharField(max_length=10)),
                ('admission1', models.CharField(max_length=2)),
                ('admission2', models.CharField(max_length=20)),
                ('admission3', models.CharField(max_length=10)),
                ('grade', models.DecimalField(decimal_places=3, max_digits=4)),
                ('univ_score', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('korean', models.DecimalField(decimal_places=3, max_digits=4)),
                ('english', models.DecimalField(decimal_places=3, max_digits=4)),
                ('mathematics', models.DecimalField(decimal_places=3, max_digits=4)),
                ('society', models.DecimalField(decimal_places=3, max_digits=4)),
                ('science', models.DecimalField(decimal_places=3, max_digits=4)),
                ('all_subject_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('all_subject_244', models.DecimalField(decimal_places=3, max_digits=4)),
                ('all_subject_433', models.DecimalField(decimal_places=3, max_digits=4)),
                ('all_subject_235', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_sci_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_sci_244', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_sci_334', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_sci_433', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_244', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_334', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_433', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_370', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_soc_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_soc_244', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_sci_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_sci_244', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_sci_334', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_sci_433', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_sci_370', models.DecimalField(decimal_places=3, max_digits=4)),
                ('en_math_sci_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('en_math_sci_244', models.DecimalField(decimal_places=3, max_digits=4)),
                ('first_step', models.CharField(max_length=5, null=True)),
                ('final_step', models.CharField(max_length=5)),
                ('fail_reason', models.CharField(max_length=10, null=True)),
                ('candidate_rank', models.IntegerField(null=True)),
                ('num_students', models.IntegerField(null=True)),
            ],
        ),
    ]
