# Generated by Django 2.2.5 on 2019-10-06 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission1', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Admission2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission2', models.CharField(max_length=10)),
                ('admission1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Admission1')),
            ],
        ),
        migrations.CreateModel(
            name='Admission3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission3', models.CharField(max_length=10)),
                ('admission1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Admission1')),
                ('admission2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Admission2')),
            ],
        ),
        migrations.CreateModel(
            name='MajorGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_group', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnel', models.IntegerField(null=True)),
                ('admission1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Admission1')),
                ('admission2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Admission2')),
            ],
        ),
        migrations.CreateModel(
            name='UnivGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ_group', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='UnivRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ_region', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='UnivName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ_name', models.CharField(max_length=10)),
                ('univ_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivGroup')),
                ('univ_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivRegion')),
            ],
        ),
        migrations.CreateModel(
            name='UnivMajor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('univ_major', models.CharField(max_length=10)),
                ('major_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.MajorGroup')),
                ('univ_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivName')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrance_year', models.IntegerField()),
                ('student_region', models.CharField(max_length=3)),
                ('grade', models.DecimalField(decimal_places=3, max_digits=4)),
                ('univ_score', models.DecimalField(decimal_places=3, max_digits=10, null=True)),
                ('korean', models.DecimalField(decimal_places=3, max_digits=4)),
                ('english', models.DecimalField(decimal_places=3, max_digits=4)),
                ('mathematics', models.DecimalField(decimal_places=3, max_digits=4)),
                ('society', models.DecimalField(decimal_places=3, max_digits=4)),
                ('science', models.DecimalField(decimal_places=3, max_digits=4)),
                ('all_subject_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('all_subject_244', models.DecimalField(decimal_places=3, max_digits=4)),
                ('all_subject_433', models.DecimalField(decimal_places=3, max_digits=4)),
                ('all_subject_235', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_sci_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_sci_244', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_sci_334', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_sci_433', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_244', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_334', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_433', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_370', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_soc_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_soc_244', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_sci_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_sci_244', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_sci_334', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_sci_433', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_sci_370', models.DecimalField(decimal_places=3, max_digits=4)),
                ('en_math_sci_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('en_math_sci_244', models.DecimalField(decimal_places=3, max_digits=4)),
                ('first_step', models.CharField(max_length=5, null=True)),
                ('final_step', models.CharField(max_length=5)),
                ('fail_reason', models.CharField(max_length=10, null=True)),
                ('candidate_rank', models.IntegerField(null=True)),
                ('admission1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Admission1')),
                ('admission2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Admission2')),
                ('admission3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Admission3')),
                ('major_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.MajorGroup')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.Personnel')),
                ('univ_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivGroup')),
                ('univ_major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivMajor')),
                ('univ_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivName')),
                ('univ_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivRegion')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='univ_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivMajor'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='univ_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivName'),
        ),
        migrations.AddField(
            model_name='admission3',
            name='univ_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivMajor'),
        ),
        migrations.AddField(
            model_name='admission3',
            name='univ_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivName'),
        ),
        migrations.AddField(
            model_name='admission2',
            name='univ_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivMajor'),
        ),
        migrations.AddField(
            model_name='admission2',
            name='univ_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivName'),
        ),
        migrations.AddField(
            model_name='admission1',
            name='univ_major',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivMajor'),
        ),
        migrations.AddField(
            model_name='admission1',
            name='univ_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.UnivName'),
        ),
    ]
