# Generated by Django 2.2.5 on 2019-09-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ibsi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ibsi_year', models.IntegerField()),
                ('gubun1', models.CharField(max_length=3)),
                ('resion', models.CharField(max_length=2)),
                ('gubun2', models.CharField(max_length=3)),
                ('univ_name', models.CharField(max_length=10)),
                ('major', models.CharField(max_length=10)),
                ('admission1', models.CharField(max_length=2)),
                ('admission2', models.CharField(max_length=20)),
                ('all_subject_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_soc_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('ko_en_math_sci_100', models.DecimalField(decimal_places=3, max_digits=4)),
                ('change_grade', models.DecimalField(decimal_places=3, max_digits=4)),
                ('first_step', models.CharField(blank=True, max_length=5)),
                ('final_step', models.CharField(max_length=5)),
                ('fail_reason', models.CharField(blank=True, max_length=10)),
                ('num_students', models.IntegerField(blank=True)),
            ],
        ),
    ]
